[pytest]
pythonpath = ["src"]

markers =
    integration: marque les tests d intégration avec la base de données

[tool:pytest]
addopts = --cov=src --cov-report=term-missing

[coverage:run]
omit =
    src/cli/*
